# 公共配置文件
# @author <a href="https://github.com/lidudulu"></a>
# @from <a href="https://dudulu.icu"></a>
server:
  port: 8123
  servlet:
    context-path: /api
yuapi:
  client:
    access-key: dudulu
    secret-key: abcdefgh